# values.yaml
module: zookeeper
environment: generic
replicas: 3

containers:
  name: zookeeper
  image: bitnami/zookeeper
  tags: latest
  ports:
    containerPort: 2181
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

service:
  type: ClusterIP
  port: 2181
  targetPort: 2181

# persistence:
#   enabled: true
#   size: 5Gi
