# templates/deployment.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- include "label-generator" . | nindent 4 }}
    module: {{ .Values.module }}
  name: {{ .Values.module }}-{{ .Values.environment }}
  # namespace: {{ .Values.module }}-{{ .Values.environment }} => défini dans le fichier values de rgocd
spec:
  serviceName: {{ .Values.module }}-{{ .Values.environment }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.module }}-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.module }}-{{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tags }}
          ports:
            - containerPort: {{ .Values.containers.ports.containerPort }}
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          resources:
            {{- toYaml .Values.containers.resources | nindent 12 }}
